version: "2.3"
services:

  elasticsearch:
    image: elasticsearch:7.6.2
    mem_limit: 1G
    container_name: elasticsearch_sample
    restart: always
    user: "0:0"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300