version: "3"

services:

  elasticsearch:
    image:          elasticsearch:8.5.3
    container_name: elasticsearch
    restart:        always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"

  kibana:
    image:          kibana:8.5.3   # http://localhost:5601/
    container_name: kibana
    ports:
      - "5601:5601"

volumes:
  elastic: {}